# Makefile

docker-compose-up-tests-integration-ltng-db:
	docker compose -f ./tests/integration/lightning-db/build/orquestrator/docker-compose.yml up -d --build

docker-compose-down-tests-integration-ltng-db:
	docker compose -f ./tests/integration/lightning-db/build/orquestrator/docker-compose.yml down
