// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mocked_ltng_client -destination ../../client/mocks/ltng_client_mock.go gitlab.com/pietroski-software-company/lightning-db/client Client
//

// Package mocked_ltng_client is a generated GoMock package.
package mocked_ltng_client

import (
	context "context"
	reflect "reflect"

	grpc_query_config "gitlab.com/pietroski-software-company/lightning-db/schemas/generated/go/common/queries/config"
	grpc_ltngdb "gitlab.com/pietroski-software-company/lightning-db/schemas/generated/go/ltngdb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CheckLightingNodeEngine mocks base method.
func (m *MockClient) CheckLightingNodeEngine(ctx context.Context, in *grpc_query_config.CheckEngineRequest, opts ...grpc.CallOption) (*grpc_query_config.CheckEngineResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckLightingNodeEngine", varargs...)
	ret0, _ := ret[0].(*grpc_query_config.CheckEngineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLightingNodeEngine indicates an expected call of CheckLightingNodeEngine.
func (mr *MockClientMockRecorder) CheckLightingNodeEngine(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLightingNodeEngine", reflect.TypeOf((*MockClient)(nil).CheckLightingNodeEngine), varargs...)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, in *grpc_ltngdb.CreateRequest, opts ...grpc.CallOption) (*grpc_ltngdb.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), varargs...)
}

// CreateStore mocks base method.
func (m *MockClient) CreateStore(ctx context.Context, in *grpc_ltngdb.CreateStoreRequest, opts ...grpc.CallOption) (*grpc_ltngdb.CreateStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateStore", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.CreateStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockClientMockRecorder) CreateStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockClient)(nil).CreateStore), varargs...)
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, in *grpc_ltngdb.DeleteRequest, opts ...grpc.CallOption) (*grpc_ltngdb.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), varargs...)
}

// DeleteStore mocks base method.
func (m *MockClient) DeleteStore(ctx context.Context, in *grpc_ltngdb.DeleteStoreRequest, opts ...grpc.CallOption) (*grpc_ltngdb.DeleteStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStore", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.DeleteStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockClientMockRecorder) DeleteStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockClient)(nil).DeleteStore), varargs...)
}

// GetStore mocks base method.
func (m *MockClient) GetStore(ctx context.Context, in *grpc_ltngdb.GetStoreRequest, opts ...grpc.CallOption) (*grpc_ltngdb.GetStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStore", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.GetStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockClientMockRecorder) GetStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockClient)(nil).GetStore), varargs...)
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, in *grpc_ltngdb.ListRequest, opts ...grpc.CallOption) (*grpc_ltngdb.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClient)(nil).List), varargs...)
}

// ListIndexingKeys mocks base method.
func (m *MockClient) ListIndexingKeys(ctx context.Context, in *grpc_ltngdb.ListValuesFromIndexingKeysRequest, opts ...grpc.CallOption) (*grpc_ltngdb.ListValuesFromIndexingKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListIndexingKeys", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.ListValuesFromIndexingKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexingKeys indicates an expected call of ListIndexingKeys.
func (mr *MockClientMockRecorder) ListIndexingKeys(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingKeys", reflect.TypeOf((*MockClient)(nil).ListIndexingKeys), varargs...)
}

// ListStores mocks base method.
func (m *MockClient) ListStores(ctx context.Context, in *grpc_ltngdb.ListStoresRequest, opts ...grpc.CallOption) (*grpc_ltngdb.ListStoresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStores", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.ListStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStores indicates an expected call of ListStores.
func (mr *MockClientMockRecorder) ListStores(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockClient)(nil).ListStores), varargs...)
}

// ListValuesFromIndexingKeys mocks base method.
func (m *MockClient) ListValuesFromIndexingKeys(ctx context.Context, in *grpc_ltngdb.ListValuesFromIndexingKeysRequest, opts ...grpc.CallOption) (*grpc_ltngdb.ListValuesFromIndexingKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListValuesFromIndexingKeys", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.ListValuesFromIndexingKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValuesFromIndexingKeys indicates an expected call of ListValuesFromIndexingKeys.
func (mr *MockClientMockRecorder) ListValuesFromIndexingKeys(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValuesFromIndexingKeys", reflect.TypeOf((*MockClient)(nil).ListValuesFromIndexingKeys), varargs...)
}

// Load mocks base method.
func (m *MockClient) Load(ctx context.Context, in *grpc_ltngdb.LoadRequest, opts ...grpc.CallOption) (*grpc_ltngdb.LoadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Load", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.LoadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockClientMockRecorder) Load(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockClient)(nil).Load), varargs...)
}

// RestartLightningNode mocks base method.
func (m *MockClient) RestartLightningNode(ctx context.Context, in *grpc_ltngdb.RestartLightningNodeRequest, opts ...grpc.CallOption) (*grpc_ltngdb.RestartLightningNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestartLightningNode", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.RestartLightningNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestartLightningNode indicates an expected call of RestartLightningNode.
func (mr *MockClientMockRecorder) RestartLightningNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartLightningNode", reflect.TypeOf((*MockClient)(nil).RestartLightningNode), varargs...)
}

// ShutdownLightningNode mocks base method.
func (m *MockClient) ShutdownLightningNode(ctx context.Context, in *grpc_ltngdb.ShutdownLightningNodeRequest, opts ...grpc.CallOption) (*grpc_ltngdb.ShutdownLightningNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShutdownLightningNode", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.ShutdownLightningNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShutdownLightningNode indicates an expected call of ShutdownLightningNode.
func (mr *MockClientMockRecorder) ShutdownLightningNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownLightningNode", reflect.TypeOf((*MockClient)(nil).ShutdownLightningNode), varargs...)
}

// Upsert mocks base method.
func (m *MockClient) Upsert(ctx context.Context, in *grpc_ltngdb.UpsertRequest, opts ...grpc.CallOption) (*grpc_ltngdb.UpsertResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(*grpc_ltngdb.UpsertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockClientMockRecorder) Upsert(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockClient)(nil).Upsert), varargs...)
}
