// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/adaptors/datastore/badgerdb/transactions/operations/indexed (interfaces: IndexedOperator)

// Package mock_indexed_operator is a generated GoMock package.
package mock_indexed_operator

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	indexed_operations "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/adaptors/datastore/badgerdb/transactions/operations/indexed"
	management_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/management"
	operation_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/operation"
	indexed_operation_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/operation/indexed"
)

// MockIndexedOperator is a mock of IndexedOperator interface.
type MockIndexedOperator struct {
	ctrl     *gomock.Controller
	recorder *MockIndexedOperatorMockRecorder
}

// MockIndexedOperatorMockRecorder is the mock recorder for MockIndexedOperator.
type MockIndexedOperatorMockRecorder struct {
	mock *MockIndexedOperator
}

// NewMockIndexedOperator creates a new mock instance.
func NewMockIndexedOperator(ctrl *gomock.Controller) *MockIndexedOperator {
	mock := &MockIndexedOperator{ctrl: ctrl}
	mock.recorder = &MockIndexedOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexedOperator) EXPECT() *MockIndexedOperatorMockRecorder {
	return m.recorder
}

// CreateIndexed mocks base method.
func (m *MockIndexedOperator) CreateIndexed(arg0 context.Context, arg1 *operation_models.OpItem, arg2 *indexed_operation_models.IdxOpsIndex) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndexed indicates an expected call of CreateIndexed.
func (mr *MockIndexedOperatorMockRecorder) CreateIndexed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexed", reflect.TypeOf((*MockIndexedOperator)(nil).CreateIndexed), arg0, arg1, arg2)
}

// DeleteIndexed mocks base method.
func (m *MockIndexedOperator) DeleteIndexed(arg0 context.Context, arg1 *operation_models.OpItem, arg2 *indexed_operation_models.IdxOpsIndex) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndexed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndexed indicates an expected call of DeleteIndexed.
func (mr *MockIndexedOperatorMockRecorder) DeleteIndexed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndexed", reflect.TypeOf((*MockIndexedOperator)(nil).DeleteIndexed), arg0, arg1, arg2)
}

// ListIndexed mocks base method.
func (m *MockIndexedOperator) ListIndexed(arg0 context.Context, arg1 *indexed_operation_models.IdxOpsIndex, arg2 *management_models.PaginationRequest) (operation_models.OpList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexed", arg0, arg1, arg2)
	ret0, _ := ret[0].(operation_models.OpList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexed indicates an expected call of ListIndexed.
func (mr *MockIndexedOperatorMockRecorder) ListIndexed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexed", reflect.TypeOf((*MockIndexedOperator)(nil).ListIndexed), arg0, arg1, arg2)
}

// LoadIndexed mocks base method.
func (m *MockIndexedOperator) LoadIndexed(arg0 context.Context, arg1 *operation_models.OpItem, arg2 *indexed_operation_models.IdxOpsIndex) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadIndexed", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadIndexed indicates an expected call of LoadIndexed.
func (mr *MockIndexedOperatorMockRecorder) LoadIndexed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadIndexed", reflect.TypeOf((*MockIndexedOperator)(nil).LoadIndexed), arg0, arg1, arg2)
}

// Operate mocks base method.
func (m *MockIndexedOperator) Operate(arg0 *management_models.DBMemoryInfo) indexed_operations.IndexedOperator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operate", arg0)
	ret0, _ := ret[0].(indexed_operations.IndexedOperator)
	return ret0
}

// Operate indicates an expected call of Operate.
func (mr *MockIndexedOperatorMockRecorder) Operate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operate", reflect.TypeOf((*MockIndexedOperator)(nil).Operate), arg0)
}

// UpdateIndexed mocks base method.
func (m *MockIndexedOperator) UpdateIndexed(arg0 context.Context, arg1 *operation_models.OpItem, arg2 *indexed_operation_models.IdxOpsIndex) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndexed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndexed indicates an expected call of UpdateIndexed.
func (mr *MockIndexedOperatorMockRecorder) UpdateIndexed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndexed", reflect.TypeOf((*MockIndexedOperator)(nil).UpdateIndexed), arg0, arg1, arg2)
}
