// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/pkg/tools/chained-operator/mocks (interfaces: Callers)
//
// Generated by this command:
//
//	mockgen -package chained_mock -destination ../../pkg/tools/chained-operator/mocks/chained_mock.go gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/pkg/tools/chained-operator/mocks Callers
//

// Package chained_mock is a generated GoMock package.
package chained_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCallers is a mock of Callers interface.
type MockCallers struct {
	ctrl     *gomock.Controller
	recorder *MockCallersMockRecorder
}

// MockCallersMockRecorder is the mock recorder for MockCallers.
type MockCallersMockRecorder struct {
	mock *MockCallers
}

// NewMockCallers creates a new mock instance.
func NewMockCallers(ctrl *gomock.Controller) *MockCallers {
	mock := &MockCallers{ctrl: ctrl}
	mock.recorder = &MockCallersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallers) EXPECT() *MockCallersMockRecorder {
	return m.recorder
}

// ActionFunc1 mocks base method.
func (m *MockCallers) ActionFunc1() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionFunc1")
	ret0, _ := ret[0].(error)
	return ret0
}

// ActionFunc1 indicates an expected call of ActionFunc1.
func (mr *MockCallersMockRecorder) ActionFunc1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionFunc1", reflect.TypeOf((*MockCallers)(nil).ActionFunc1))
}

// ActionFunc2 mocks base method.
func (m *MockCallers) ActionFunc2() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionFunc2")
	ret0, _ := ret[0].(error)
	return ret0
}

// ActionFunc2 indicates an expected call of ActionFunc2.
func (mr *MockCallersMockRecorder) ActionFunc2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionFunc2", reflect.TypeOf((*MockCallers)(nil).ActionFunc2))
}

// ActionFunc3 mocks base method.
func (m *MockCallers) ActionFunc3() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionFunc3")
	ret0, _ := ret[0].(error)
	return ret0
}

// ActionFunc3 indicates an expected call of ActionFunc3.
func (mr *MockCallersMockRecorder) ActionFunc3() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionFunc3", reflect.TypeOf((*MockCallers)(nil).ActionFunc3))
}

// RollbackActionFunc1 mocks base method.
func (m *MockCallers) RollbackActionFunc1() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackActionFunc1")
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackActionFunc1 indicates an expected call of RollbackActionFunc1.
func (mr *MockCallersMockRecorder) RollbackActionFunc1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackActionFunc1", reflect.TypeOf((*MockCallers)(nil).RollbackActionFunc1))
}

// RollbackActionFunc2 mocks base method.
func (m *MockCallers) RollbackActionFunc2() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackActionFunc2")
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackActionFunc2 indicates an expected call of RollbackActionFunc2.
func (mr *MockCallersMockRecorder) RollbackActionFunc2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackActionFunc2", reflect.TypeOf((*MockCallers)(nil).RollbackActionFunc2))
}
