// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/internal/adaptors/datastore/badgerdb/manager (interfaces: Manager)

// Package mock_manager is a generated GoMock package.
package mock_manager

import (
	context "context"
	reflect "reflect"

	badger "github.com/dgraph-io/badger/v3"
	gomock "github.com/golang/mock/gomock"
	management_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/internal/models/management"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateOpenStoreAndLoadIntoMemory mocks base method.
func (m *MockManager) CreateOpenStoreAndLoadIntoMemory(arg0 *management_models.DBInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenStoreAndLoadIntoMemory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOpenStoreAndLoadIntoMemory indicates an expected call of CreateOpenStoreAndLoadIntoMemory.
func (mr *MockManagerMockRecorder) CreateOpenStoreAndLoadIntoMemory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenStoreAndLoadIntoMemory", reflect.TypeOf((*MockManager)(nil).CreateOpenStoreAndLoadIntoMemory), arg0)
}

// DeleteFromMemoryAndDisk mocks base method.
func (m *MockManager) DeleteFromMemoryAndDisk(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromMemoryAndDisk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFromMemoryAndDisk indicates an expected call of DeleteFromMemoryAndDisk.
func (mr *MockManagerMockRecorder) DeleteFromMemoryAndDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromMemoryAndDisk", reflect.TypeOf((*MockManager)(nil).DeleteFromMemoryAndDisk), arg0, arg1)
}

// GetDBInfo mocks base method.
func (m *MockManager) GetDBInfo(arg0 context.Context, arg1 string) (*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBInfo indicates an expected call of GetDBInfo.
func (mr *MockManagerMockRecorder) GetDBInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBInfo", reflect.TypeOf((*MockManager)(nil).GetDBInfo), arg0, arg1)
}

// GetDBMemoryInfo mocks base method.
func (m *MockManager) GetDBMemoryInfo(arg0 context.Context, arg1 string) (*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBMemoryInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBMemoryInfo indicates an expected call of GetDBMemoryInfo.
func (mr *MockManagerMockRecorder) GetDBMemoryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBMemoryInfo", reflect.TypeOf((*MockManager)(nil).GetDBMemoryInfo), arg0, arg1)
}

// GetStoreInfoFromMemoryOrFromDisk mocks base method.
func (m *MockManager) GetStoreInfoFromMemoryOrFromDisk(arg0 context.Context, arg1 string) (*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreInfoFromMemoryOrFromDisk", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreInfoFromMemoryOrFromDisk indicates an expected call of GetStoreInfoFromMemoryOrFromDisk.
func (mr *MockManagerMockRecorder) GetStoreInfoFromMemoryOrFromDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreInfoFromMemoryOrFromDisk", reflect.TypeOf((*MockManager)(nil).GetStoreInfoFromMemoryOrFromDisk), arg0, arg1)
}

// GetStoreMemoryInfoFromMemoryOrDisk mocks base method.
func (m *MockManager) GetStoreMemoryInfoFromMemoryOrDisk(arg0 context.Context, arg1 string) (*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreMemoryInfoFromMemoryOrDisk", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreMemoryInfoFromMemoryOrDisk indicates an expected call of GetStoreMemoryInfoFromMemoryOrDisk.
func (mr *MockManagerMockRecorder) GetStoreMemoryInfoFromMemoryOrDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreMemoryInfoFromMemoryOrDisk", reflect.TypeOf((*MockManager)(nil).GetStoreMemoryInfoFromMemoryOrDisk), arg0, arg1)
}

// ListStoreInfoFromMemoryOrDisk mocks base method.
func (m *MockManager) ListStoreInfoFromMemoryOrDisk(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreInfoFromMemoryOrDisk", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreInfoFromMemoryOrDisk indicates an expected call of ListStoreInfoFromMemoryOrDisk.
func (mr *MockManagerMockRecorder) ListStoreInfoFromMemoryOrDisk(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreInfoFromMemoryOrDisk", reflect.TypeOf((*MockManager)(nil).ListStoreInfoFromMemoryOrDisk), arg0, arg1, arg2)
}

// ListStoreMemoryInfoFromMemoryOrDisk mocks base method.
func (m *MockManager) ListStoreMemoryInfoFromMemoryOrDisk(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreMemoryInfoFromMemoryOrDisk", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreMemoryInfoFromMemoryOrDisk indicates an expected call of ListStoreMemoryInfoFromMemoryOrDisk.
func (mr *MockManagerMockRecorder) ListStoreMemoryInfoFromMemoryOrDisk(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreMemoryInfoFromMemoryOrDisk", reflect.TypeOf((*MockManager)(nil).ListStoreMemoryInfoFromMemoryOrDisk), arg0, arg1, arg2)
}

// Paginate mocks base method.
func (m *MockManager) Paginate(arg0 *badger.Iterator, arg1, arg2 int) *badger.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*badger.Iterator)
	return ret0
}

// Paginate indicates an expected call of Paginate.
func (mr *MockManagerMockRecorder) Paginate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockManager)(nil).Paginate), arg0, arg1, arg2)
}

// Restart mocks base method.
func (m *MockManager) Restart() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart")
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockManagerMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockManager)(nil).Restart))
}

// Shutdown mocks base method.
func (m *MockManager) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockManager)(nil).Shutdown))
}

// ShutdownStores mocks base method.
func (m *MockManager) ShutdownStores() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShutdownStores")
}

// ShutdownStores indicates an expected call of ShutdownStores.
func (mr *MockManagerMockRecorder) ShutdownStores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownStores", reflect.TypeOf((*MockManager)(nil).ShutdownStores))
}

// Start mocks base method.
func (m *MockManager) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager)(nil).Start))
}

// ValidatePagination mocks base method.
func (m *MockManager) ValidatePagination(arg0, arg1 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePagination", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePagination indicates an expected call of ValidatePagination.
func (mr *MockManagerMockRecorder) ValidatePagination(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePagination", reflect.TypeOf((*MockManager)(nil).ValidatePagination), arg0, arg1)
}
