// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/pkg/client (interfaces: LTNGClient)

// Package mocked_ltng_client is a generated GoMock package.
package mocked_ltng_client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc_query_config "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/schemas/generated/go/common/queries/config"
	grpc_mngmt "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/schemas/generated/go/management"
	grpc_ops "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/schemas/generated/go/transactions/operations"
	grpc "google.golang.org/grpc"
)

// MockLTNGClient is a mock of LTNGClient interface.
type MockLTNGClient struct {
	ctrl     *gomock.Controller
	recorder *MockLTNGClientMockRecorder
}

// MockLTNGClientMockRecorder is the mock recorder for MockLTNGClient.
type MockLTNGClientMockRecorder struct {
	mock *MockLTNGClient
}

// NewMockLTNGClient creates a new mock instance.
func NewMockLTNGClient(ctrl *gomock.Controller) *MockLTNGClient {
	mock := &MockLTNGClient{ctrl: ctrl}
	mock.recorder = &MockLTNGClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLTNGClient) EXPECT() *MockLTNGClientMockRecorder {
	return m.recorder
}

// CheckManagerEngine mocks base method.
func (m *MockLTNGClient) CheckManagerEngine(arg0 context.Context, arg1 *grpc_query_config.CheckEngineRequest, arg2 ...grpc.CallOption) (*grpc_query_config.CheckEngineResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckManagerEngine", varargs...)
	ret0, _ := ret[0].(*grpc_query_config.CheckEngineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckManagerEngine indicates an expected call of CheckManagerEngine.
func (mr *MockLTNGClientMockRecorder) CheckManagerEngine(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckManagerEngine", reflect.TypeOf((*MockLTNGClient)(nil).CheckManagerEngine), varargs...)
}

// CheckOperatorEngine mocks base method.
func (m *MockLTNGClient) CheckOperatorEngine(arg0 context.Context, arg1 *grpc_query_config.CheckEngineRequest, arg2 ...grpc.CallOption) (*grpc_query_config.CheckEngineResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckOperatorEngine", varargs...)
	ret0, _ := ret[0].(*grpc_query_config.CheckEngineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOperatorEngine indicates an expected call of CheckOperatorEngine.
func (mr *MockLTNGClientMockRecorder) CheckOperatorEngine(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOperatorEngine", reflect.TypeOf((*MockLTNGClient)(nil).CheckOperatorEngine), varargs...)
}

// Close mocks base method.
func (m *MockLTNGClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLTNGClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLTNGClient)(nil).Close))
}

// Create mocks base method.
func (m *MockLTNGClient) Create(arg0 context.Context, arg1 *grpc_ops.CreateRequest, arg2 ...grpc.CallOption) (*grpc_ops.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*grpc_ops.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLTNGClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLTNGClient)(nil).Create), varargs...)
}

// CreateStore mocks base method.
func (m *MockLTNGClient) CreateStore(arg0 context.Context, arg1 *grpc_mngmt.CreateStoreRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.CreateStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateStore", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.CreateStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockLTNGClientMockRecorder) CreateStore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockLTNGClient)(nil).CreateStore), varargs...)
}

// Delete mocks base method.
func (m *MockLTNGClient) Delete(arg0 context.Context, arg1 *grpc_ops.DeleteRequest, arg2 ...grpc.CallOption) (*grpc_ops.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*grpc_ops.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockLTNGClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLTNGClient)(nil).Delete), varargs...)
}

// DeleteStore mocks base method.
func (m *MockLTNGClient) DeleteStore(arg0 context.Context, arg1 *grpc_mngmt.DeleteStoreRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.DeleteStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStore", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.DeleteStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockLTNGClientMockRecorder) DeleteStore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockLTNGClient)(nil).DeleteStore), varargs...)
}

// GetStore mocks base method.
func (m *MockLTNGClient) GetStore(arg0 context.Context, arg1 *grpc_mngmt.GetStoreRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.GetStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStore", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.GetStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockLTNGClientMockRecorder) GetStore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockLTNGClient)(nil).GetStore), varargs...)
}

// List mocks base method.
func (m *MockLTNGClient) List(arg0 context.Context, arg1 *grpc_ops.ListRequest, arg2 ...grpc.CallOption) (*grpc_ops.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*grpc_ops.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLTNGClientMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLTNGClient)(nil).List), varargs...)
}

// ListStores mocks base method.
func (m *MockLTNGClient) ListStores(arg0 context.Context, arg1 *grpc_mngmt.ListStoresRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.ListStoresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStores", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.ListStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStores indicates an expected call of ListStores.
func (mr *MockLTNGClientMockRecorder) ListStores(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockLTNGClient)(nil).ListStores), varargs...)
}

// ListValuesFromIndexingKeys mocks base method.
func (m *MockLTNGClient) ListValuesFromIndexingKeys(arg0 context.Context, arg1 *grpc_ops.ListValuesFromIndexingKeysRequest, arg2 ...grpc.CallOption) (*grpc_ops.ListValuesFromIndexingKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListValuesFromIndexingKeys", varargs...)
	ret0, _ := ret[0].(*grpc_ops.ListValuesFromIndexingKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValuesFromIndexingKeys indicates an expected call of ListValuesFromIndexingKeys.
func (mr *MockLTNGClientMockRecorder) ListValuesFromIndexingKeys(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValuesFromIndexingKeys", reflect.TypeOf((*MockLTNGClient)(nil).ListValuesFromIndexingKeys), varargs...)
}

// Load mocks base method.
func (m *MockLTNGClient) Load(arg0 context.Context, arg1 *grpc_ops.LoadRequest, arg2 ...grpc.CallOption) (*grpc_ops.LoadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Load", varargs...)
	ret0, _ := ret[0].(*grpc_ops.LoadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockLTNGClientMockRecorder) Load(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLTNGClient)(nil).Load), varargs...)
}

// RestartLightningNode mocks base method.
func (m *MockLTNGClient) RestartLightningNode(arg0 context.Context, arg1 *grpc_mngmt.RestartLightningNodeRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.RestartLightningNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestartLightningNode", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.RestartLightningNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestartLightningNode indicates an expected call of RestartLightningNode.
func (mr *MockLTNGClientMockRecorder) RestartLightningNode(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartLightningNode", reflect.TypeOf((*MockLTNGClient)(nil).RestartLightningNode), varargs...)
}

// ShutdownLightningNode mocks base method.
func (m *MockLTNGClient) ShutdownLightningNode(arg0 context.Context, arg1 *grpc_mngmt.ShutdownLightningNodeRequest, arg2 ...grpc.CallOption) (*grpc_mngmt.ShutdownLightningNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShutdownLightningNode", varargs...)
	ret0, _ := ret[0].(*grpc_mngmt.ShutdownLightningNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShutdownLightningNode indicates an expected call of ShutdownLightningNode.
func (mr *MockLTNGClientMockRecorder) ShutdownLightningNode(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownLightningNode", reflect.TypeOf((*MockLTNGClient)(nil).ShutdownLightningNode), varargs...)
}

// Upsert mocks base method.
func (m *MockLTNGClient) Upsert(arg0 context.Context, arg1 *grpc_ops.UpsertRequest, arg2 ...grpc.CallOption) (*grpc_ops.UpsertResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(*grpc_ops.UpsertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockLTNGClientMockRecorder) Upsert(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockLTNGClient)(nil).Upsert), varargs...)
}
