// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4/transactions/operations (interfaces: Operator)
//
// Generated by this command:
//
//	mockgen -package mock_badgerdb_operations_adaptor_v4 -destination ../../internal/adaptors/datastore/badgerdb/v4/transactions/operations/mocks/operations.go gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4/transactions/operations Operator
//

// Package mock_badgerdb_operations_adaptor_v4 is a generated GoMock package.
package mock_badgerdb_operations_adaptor_v4

import (
	context "context"
	reflect "reflect"

	badgerdb_operations_adaptor_v4 "gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4/transactions/operations"
	models_badgerdb_v4_management "gitlab.com/pietroski-software-company/lightning-db/internal/models/badgerdb/v4/management"
	models_badgerdb_v4_operation "gitlab.com/pietroski-software-company/lightning-db/internal/models/badgerdb/v4/operation"
	list_operator "gitlab.com/pietroski-software-company/lightning-db/pkg/tools/list-operator"
	gomock "go.uber.org/mock/gomock"
)

// MockOperator is a mock of Operator interface.
type MockOperator struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorMockRecorder
}

// MockOperatorMockRecorder is the mock recorder for MockOperator.
type MockOperatorMockRecorder struct {
	mock *MockOperator
}

// NewMockOperator creates a new mock instance.
func NewMockOperator(ctrl *gomock.Controller) *MockOperator {
	mock := &MockOperator{ctrl: ctrl}
	mock.recorder = &MockOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperator) EXPECT() *MockOperatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOperator) Create(arg0 context.Context, arg1 *models_badgerdb_v4_operation.Item, arg2 *models_badgerdb_v4_operation.IndexOpts, arg3 *list_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOperatorMockRecorder) Create(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperator)(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockOperator) Delete(arg0 context.Context, arg1 *models_badgerdb_v4_operation.Item, arg2 *models_badgerdb_v4_operation.IndexOpts, arg3 *list_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOperatorMockRecorder) Delete(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOperator)(nil).Delete), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockOperator) List(arg0 context.Context, arg1 *models_badgerdb_v4_operation.IndexOpts, arg2 *models_badgerdb_v4_management.Pagination) (models_badgerdb_v4_operation.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].(models_badgerdb_v4_operation.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOperatorMockRecorder) List(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperator)(nil).List), arg0, arg1, arg2)
}

// ListValuesFromIndexingKeys mocks base method.
func (m *MockOperator) ListValuesFromIndexingKeys(arg0 context.Context, arg1 *models_badgerdb_v4_operation.IndexOpts) (models_badgerdb_v4_operation.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListValuesFromIndexingKeys", arg0, arg1)
	ret0, _ := ret[0].(models_badgerdb_v4_operation.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValuesFromIndexingKeys indicates an expected call of ListValuesFromIndexingKeys.
func (mr *MockOperatorMockRecorder) ListValuesFromIndexingKeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValuesFromIndexingKeys", reflect.TypeOf((*MockOperator)(nil).ListValuesFromIndexingKeys), arg0, arg1)
}

// Load mocks base method.
func (m *MockOperator) Load(arg0 context.Context, arg1 *models_badgerdb_v4_operation.Item, arg2 *models_badgerdb_v4_operation.IndexOpts) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOperatorMockRecorder) Load(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOperator)(nil).Load), arg0, arg1, arg2)
}

// Operate mocks base method.
func (m *MockOperator) Operate(arg0 *models_badgerdb_v4_management.DBMemoryInfo) badgerdb_operations_adaptor_v4.Operator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operate", arg0)
	ret0, _ := ret[0].(badgerdb_operations_adaptor_v4.Operator)
	return ret0
}

// Operate indicates an expected call of Operate.
func (mr *MockOperatorMockRecorder) Operate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operate", reflect.TypeOf((*MockOperator)(nil).Operate), arg0)
}

// Upsert mocks base method.
func (m *MockOperator) Upsert(arg0 context.Context, arg1 *models_badgerdb_v4_operation.Item, arg2 *models_badgerdb_v4_operation.IndexOpts, arg3 *list_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOperatorMockRecorder) Upsert(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOperator)(nil).Upsert), arg0, arg1, arg2, arg3)
}
