// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/adaptors/datastore/badgerdb/manager/indexed (interfaces: IndexerManager)

// Package mock_indexed_manager is a generated GoMock package.
package mock_indexed_manager

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	management_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/management"
)

// MockIndexerManager is a mock of IndexerManager interface.
type MockIndexerManager struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerManagerMockRecorder
}

// MockIndexerManagerMockRecorder is the mock recorder for MockIndexerManager.
type MockIndexerManagerMockRecorder struct {
	mock *MockIndexerManager
}

// NewMockIndexerManager creates a new mock instance.
func NewMockIndexerManager(ctrl *gomock.Controller) *MockIndexerManager {
	mock := &MockIndexerManager{ctrl: ctrl}
	mock.recorder = &MockIndexerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexerManager) EXPECT() *MockIndexerManagerMockRecorder {
	return m.recorder
}

// CreateIndexedStore mocks base method.
func (m *MockIndexerManager) CreateIndexedStore(arg0 context.Context, arg1 *management_models.DBInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexedStore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndexedStore indicates an expected call of CreateIndexedStore.
func (mr *MockIndexerManagerMockRecorder) CreateIndexedStore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexedStore", reflect.TypeOf((*MockIndexerManager)(nil).CreateIndexedStore), arg0, arg1)
}

// DeleteIndexedStore mocks base method.
func (m *MockIndexerManager) DeleteIndexedStore(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndexedStore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndexedStore indicates an expected call of DeleteIndexedStore.
func (mr *MockIndexerManagerMockRecorder) DeleteIndexedStore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndexedStore", reflect.TypeOf((*MockIndexerManager)(nil).DeleteIndexedStore), arg0, arg1)
}

// GetDBAndIndexedDBInfo mocks base method.
func (m *MockIndexerManager) GetDBAndIndexedDBInfo(arg0 context.Context, arg1 string) (*management_models.DBInfo, *management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBAndIndexedDBInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBInfo)
	ret1, _ := ret[1].(*management_models.DBInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDBAndIndexedDBInfo indicates an expected call of GetDBAndIndexedDBInfo.
func (mr *MockIndexerManagerMockRecorder) GetDBAndIndexedDBInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBAndIndexedDBInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetDBAndIndexedDBInfo), arg0, arg1)
}

// GetDBAndIndexedDBMemoryInfo mocks base method.
func (m *MockIndexerManager) GetDBAndIndexedDBMemoryInfo(arg0 context.Context, arg1 string) (*management_models.DBMemoryInfo, *management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBAndIndexedDBMemoryInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(*management_models.DBMemoryInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDBAndIndexedDBMemoryInfo indicates an expected call of GetDBAndIndexedDBMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) GetDBAndIndexedDBMemoryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBAndIndexedDBMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetDBAndIndexedDBMemoryInfo), arg0, arg1)
}

// GetDBInfo mocks base method.
func (m *MockIndexerManager) GetDBInfo(arg0 context.Context, arg1 string) (*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBInfo indicates an expected call of GetDBInfo.
func (mr *MockIndexerManagerMockRecorder) GetDBInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetDBInfo), arg0, arg1)
}

// GetDBMemoryInfo mocks base method.
func (m *MockIndexerManager) GetDBMemoryInfo(arg0 context.Context, arg1 string) (*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBMemoryInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBMemoryInfo indicates an expected call of GetDBMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) GetDBMemoryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetDBMemoryInfo), arg0, arg1)
}

// GetIndexedDBInfo mocks base method.
func (m *MockIndexerManager) GetIndexedDBInfo(arg0 context.Context, arg1 string) (*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexedDBInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexedDBInfo indicates an expected call of GetIndexedDBInfo.
func (mr *MockIndexerManagerMockRecorder) GetIndexedDBInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexedDBInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetIndexedDBInfo), arg0, arg1)
}

// GetIndexedDBMemoryInfo mocks base method.
func (m *MockIndexerManager) GetIndexedDBMemoryInfo(arg0 context.Context, arg1 string) (*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexedDBMemoryInfo", arg0, arg1)
	ret0, _ := ret[0].(*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexedDBMemoryInfo indicates an expected call of GetIndexedDBMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) GetIndexedDBMemoryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexedDBMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).GetIndexedDBMemoryInfo), arg0, arg1)
}

// ListIndexedStoreInfo mocks base method.
func (m *MockIndexerManager) ListIndexedStoreInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexedStoreInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexedStoreInfo indicates an expected call of ListIndexedStoreInfo.
func (mr *MockIndexerManagerMockRecorder) ListIndexedStoreInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexedStoreInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListIndexedStoreInfo), arg0, arg1, arg2)
}

// ListIndexedStoreMemoryInfo mocks base method.
func (m *MockIndexerManager) ListIndexedStoreMemoryInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexedStoreMemoryInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexedStoreMemoryInfo indicates an expected call of ListIndexedStoreMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) ListIndexedStoreMemoryInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexedStoreMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListIndexedStoreMemoryInfo), arg0, arg1, arg2)
}

// ListStoreAndIndexedStoreInfo mocks base method.
func (m *MockIndexerManager) ListStoreAndIndexedStoreInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBInfo, []*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreAndIndexedStoreInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBInfo)
	ret1, _ := ret[1].([]*management_models.DBInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStoreAndIndexedStoreInfo indicates an expected call of ListStoreAndIndexedStoreInfo.
func (mr *MockIndexerManagerMockRecorder) ListStoreAndIndexedStoreInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreAndIndexedStoreInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListStoreAndIndexedStoreInfo), arg0, arg1, arg2)
}

// ListStoreAndIndexedStoreMemoryInfo mocks base method.
func (m *MockIndexerManager) ListStoreAndIndexedStoreMemoryInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBMemoryInfo, []*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreAndIndexedStoreMemoryInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBMemoryInfo)
	ret1, _ := ret[1].([]*management_models.DBMemoryInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStoreAndIndexedStoreMemoryInfo indicates an expected call of ListStoreAndIndexedStoreMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) ListStoreAndIndexedStoreMemoryInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreAndIndexedStoreMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListStoreAndIndexedStoreMemoryInfo), arg0, arg1, arg2)
}

// ListStoreInfo mocks base method.
func (m *MockIndexerManager) ListStoreInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreInfo indicates an expected call of ListStoreInfo.
func (mr *MockIndexerManagerMockRecorder) ListStoreInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListStoreInfo), arg0, arg1, arg2)
}

// ListStoreMemoryInfo mocks base method.
func (m *MockIndexerManager) ListStoreMemoryInfo(arg0 context.Context, arg1, arg2 int) ([]*management_models.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreMemoryInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*management_models.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreMemoryInfo indicates an expected call of ListStoreMemoryInfo.
func (mr *MockIndexerManagerMockRecorder) ListStoreMemoryInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreMemoryInfo", reflect.TypeOf((*MockIndexerManager)(nil).ListStoreMemoryInfo), arg0, arg1, arg2)
}
