// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/adaptors/datastore/badgerdb/transactions/operations (interfaces: Operator)

// Package mock_operations is a generated GoMock package.
package mock_operations

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	operations "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/adaptors/datastore/badgerdb/transactions/operations"
	management_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/management"
	operation_models "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/internal/models/operation"
	chainded_operator "gitlab.com/pietroski-software-company/lightning-db/lightning-node/go-lightning-node/pkg/tools/chained-operator"
)

// MockOperator is a mock of Operator interface.
type MockOperator struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorMockRecorder
}

// MockOperatorMockRecorder is the mock recorder for MockOperator.
type MockOperatorMockRecorder struct {
	mock *MockOperator
}

// NewMockOperator creates a new mock instance.
func NewMockOperator(ctrl *gomock.Controller) *MockOperator {
	mock := &MockOperator{ctrl: ctrl}
	mock.recorder = &MockOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperator) EXPECT() *MockOperatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOperator) Create(arg0 context.Context, arg1 *operation_models.Item, arg2 *operation_models.IndexOpts, arg3 *chainded_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOperatorMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperator)(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockOperator) Delete(arg0 context.Context, arg1 *operation_models.Item, arg2 *operation_models.IndexOpts, arg3 *chainded_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOperatorMockRecorder) Delete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOperator)(nil).Delete), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockOperator) List(arg0 *operation_models.IndexOpts, arg1 *management_models.Pagination) (operation_models.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(operation_models.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOperatorMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperator)(nil).List), arg0, arg1)
}

// ListValuesFromIndexingKeys mocks base method.
func (m *MockOperator) ListValuesFromIndexingKeys(arg0 context.Context, arg1 *operation_models.IndexOpts) (operation_models.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListValuesFromIndexingKeys", arg0, arg1)
	ret0, _ := ret[0].(operation_models.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValuesFromIndexingKeys indicates an expected call of ListValuesFromIndexingKeys.
func (mr *MockOperatorMockRecorder) ListValuesFromIndexingKeys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValuesFromIndexingKeys", reflect.TypeOf((*MockOperator)(nil).ListValuesFromIndexingKeys), arg0, arg1)
}

// Load mocks base method.
func (m *MockOperator) Load(arg0 context.Context, arg1 *operation_models.Item, arg2 *operation_models.IndexOpts) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOperatorMockRecorder) Load(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOperator)(nil).Load), arg0, arg1, arg2)
}

// Operate mocks base method.
func (m *MockOperator) Operate(arg0 *management_models.DBMemoryInfo) operations.Operator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operate", arg0)
	ret0, _ := ret[0].(operations.Operator)
	return ret0
}

// Operate indicates an expected call of Operate.
func (mr *MockOperatorMockRecorder) Operate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operate", reflect.TypeOf((*MockOperator)(nil).Operate), arg0)
}

// Upsert mocks base method.
func (m *MockOperator) Upsert(arg0 context.Context, arg1 *operation_models.Item, arg2 *operation_models.IndexOpts, arg3 *chainded_operator.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOperatorMockRecorder) Upsert(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOperator)(nil).Upsert), arg0, arg1, arg2, arg3)
}
