// Code generated by counterfeiter. DO NOT EDIT.
package go_cache

import (
	"context"
	"sync"

	go_cache "gitlab.com/pietroski-software-company/lightning-db/pkg/tools/cache"
)

type FakeCacher struct {
	DelStub        func(context.Context, string) error
	delMutex       sync.RWMutex
	delArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	delReturns struct {
		result1 error
	}
	delReturnsOnCall map[int]struct {
		result1 error
	}
	DelFromPatternStub        func(context.Context, string) error
	delFromPatternMutex       sync.RWMutex
	delFromPatternArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	delFromPatternReturns struct {
		result1 error
	}
	delFromPatternReturnsOnCall map[int]struct {
		result1 error
	}
	DelFromPatternSyncStub        func(context.Context, string) error
	delFromPatternSyncMutex       sync.RWMutex
	delFromPatternSyncArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	delFromPatternSyncReturns struct {
		result1 error
	}
	delFromPatternSyncReturnsOnCall map[int]struct {
		result1 error
	}
	GetStub        func(context.Context, string, interface{}, go_cache.Fallback) error
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 interface{}
		arg4 go_cache.Fallback
	}
	getReturns struct {
		result1 error
	}
	getReturnsOnCall map[int]struct {
		result1 error
	}
	SetStub        func(context.Context, string, interface{}) error
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 interface{}
	}
	setReturns struct {
		result1 error
	}
	setReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCacher) Del(arg1 context.Context, arg2 string) error {
	fake.delMutex.Lock()
	ret, specificReturn := fake.delReturnsOnCall[len(fake.delArgsForCall)]
	fake.delArgsForCall = append(fake.delArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DelStub
	fakeReturns := fake.delReturns
	fake.recordInvocation("Del", []interface{}{arg1, arg2})
	fake.delMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacher) DelCallCount() int {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	return len(fake.delArgsForCall)
}

func (fake *FakeCacher) DelCalls(stub func(context.Context, string) error) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = stub
}

func (fake *FakeCacher) DelArgsForCall(i int) (context.Context, string) {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	argsForCall := fake.delArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCacher) DelReturns(result1 error) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	fake.delReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) DelReturnsOnCall(i int, result1 error) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	if fake.delReturnsOnCall == nil {
		fake.delReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.delReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) DelFromPattern(arg1 context.Context, arg2 string) error {
	fake.delFromPatternMutex.Lock()
	ret, specificReturn := fake.delFromPatternReturnsOnCall[len(fake.delFromPatternArgsForCall)]
	fake.delFromPatternArgsForCall = append(fake.delFromPatternArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DelFromPatternStub
	fakeReturns := fake.delFromPatternReturns
	fake.recordInvocation("DelFromPattern", []interface{}{arg1, arg2})
	fake.delFromPatternMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacher) DelFromPatternCallCount() int {
	fake.delFromPatternMutex.RLock()
	defer fake.delFromPatternMutex.RUnlock()
	return len(fake.delFromPatternArgsForCall)
}

func (fake *FakeCacher) DelFromPatternCalls(stub func(context.Context, string) error) {
	fake.delFromPatternMutex.Lock()
	defer fake.delFromPatternMutex.Unlock()
	fake.DelFromPatternStub = stub
}

func (fake *FakeCacher) DelFromPatternArgsForCall(i int) (context.Context, string) {
	fake.delFromPatternMutex.RLock()
	defer fake.delFromPatternMutex.RUnlock()
	argsForCall := fake.delFromPatternArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCacher) DelFromPatternReturns(result1 error) {
	fake.delFromPatternMutex.Lock()
	defer fake.delFromPatternMutex.Unlock()
	fake.DelFromPatternStub = nil
	fake.delFromPatternReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) DelFromPatternReturnsOnCall(i int, result1 error) {
	fake.delFromPatternMutex.Lock()
	defer fake.delFromPatternMutex.Unlock()
	fake.DelFromPatternStub = nil
	if fake.delFromPatternReturnsOnCall == nil {
		fake.delFromPatternReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.delFromPatternReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) DelFromPatternSync(arg1 context.Context, arg2 string) error {
	fake.delFromPatternSyncMutex.Lock()
	ret, specificReturn := fake.delFromPatternSyncReturnsOnCall[len(fake.delFromPatternSyncArgsForCall)]
	fake.delFromPatternSyncArgsForCall = append(fake.delFromPatternSyncArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DelFromPatternSyncStub
	fakeReturns := fake.delFromPatternSyncReturns
	fake.recordInvocation("DelFromPatternSync", []interface{}{arg1, arg2})
	fake.delFromPatternSyncMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacher) DelFromPatternSyncCallCount() int {
	fake.delFromPatternSyncMutex.RLock()
	defer fake.delFromPatternSyncMutex.RUnlock()
	return len(fake.delFromPatternSyncArgsForCall)
}

func (fake *FakeCacher) DelFromPatternSyncCalls(stub func(context.Context, string) error) {
	fake.delFromPatternSyncMutex.Lock()
	defer fake.delFromPatternSyncMutex.Unlock()
	fake.DelFromPatternSyncStub = stub
}

func (fake *FakeCacher) DelFromPatternSyncArgsForCall(i int) (context.Context, string) {
	fake.delFromPatternSyncMutex.RLock()
	defer fake.delFromPatternSyncMutex.RUnlock()
	argsForCall := fake.delFromPatternSyncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCacher) DelFromPatternSyncReturns(result1 error) {
	fake.delFromPatternSyncMutex.Lock()
	defer fake.delFromPatternSyncMutex.Unlock()
	fake.DelFromPatternSyncStub = nil
	fake.delFromPatternSyncReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) DelFromPatternSyncReturnsOnCall(i int, result1 error) {
	fake.delFromPatternSyncMutex.Lock()
	defer fake.delFromPatternSyncMutex.Unlock()
	fake.DelFromPatternSyncStub = nil
	if fake.delFromPatternSyncReturnsOnCall == nil {
		fake.delFromPatternSyncReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.delFromPatternSyncReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) Get(arg1 context.Context, arg2 string, arg3 interface{}, arg4 go_cache.Fallback) error {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 interface{}
		arg4 go_cache.Fallback
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2, arg3, arg4})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacher) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeCacher) GetCalls(stub func(context.Context, string, interface{}, go_cache.Fallback) error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeCacher) GetArgsForCall(i int) (context.Context, string, interface{}, go_cache.Fallback) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeCacher) GetReturns(result1 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) GetReturnsOnCall(i int, result1 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) Set(arg1 context.Context, arg2 string, arg3 interface{}) error {
	fake.setMutex.Lock()
	ret, specificReturn := fake.setReturnsOnCall[len(fake.setArgsForCall)]
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 interface{}
	}{arg1, arg2, arg3})
	stub := fake.SetStub
	fakeReturns := fake.setReturns
	fake.recordInvocation("Set", []interface{}{arg1, arg2, arg3})
	fake.setMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacher) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *FakeCacher) SetCalls(stub func(context.Context, string, interface{}) error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *FakeCacher) SetArgsForCall(i int) (context.Context, string, interface{}) {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCacher) SetReturns(result1 error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	fake.setReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) SetReturnsOnCall(i int, result1 error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	if fake.setReturnsOnCall == nil {
		fake.setReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	fake.delFromPatternMutex.RLock()
	defer fake.delFromPatternMutex.RUnlock()
	fake.delFromPatternSyncMutex.RLock()
	defer fake.delFromPatternSyncMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCacher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ go_cache.Cacher = new(FakeCacher)
