// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4 (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ../../internal/adaptors/datastore/badgerdb/v4/mocks/manager.go gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4 Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	badger "github.com/dgraph-io/badger/v4"
	models_badgerdb_v4_management "gitlab.com/pietroski-software-company/lightning-db/internal/models/badgerdb/v4/management"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateStore mocks base method.
func (m *MockManager) CreateStore(ctx context.Context, info *models_badgerdb_v4_management.DBInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockManagerMockRecorder) CreateStore(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockManager)(nil).CreateStore), ctx, info)
}

// DeleteStore mocks base method.
func (m *MockManager) DeleteStore(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStore", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockManagerMockRecorder) DeleteStore(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockManager)(nil).DeleteStore), ctx, name)
}

// GetDBInfo mocks base method.
func (m *MockManager) GetDBInfo(ctx context.Context, name string) (*models_badgerdb_v4_management.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBInfo", ctx, name)
	ret0, _ := ret[0].(*models_badgerdb_v4_management.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBInfo indicates an expected call of GetDBInfo.
func (mr *MockManagerMockRecorder) GetDBInfo(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBInfo", reflect.TypeOf((*MockManager)(nil).GetDBInfo), ctx, name)
}

// GetDBMemoryInfo mocks base method.
func (m *MockManager) GetDBMemoryInfo(ctx context.Context, name string) (*models_badgerdb_v4_management.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBMemoryInfo", ctx, name)
	ret0, _ := ret[0].(*models_badgerdb_v4_management.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBMemoryInfo indicates an expected call of GetDBMemoryInfo.
func (mr *MockManagerMockRecorder) GetDBMemoryInfo(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBMemoryInfo", reflect.TypeOf((*MockManager)(nil).GetDBMemoryInfo), ctx, name)
}

// ListStoreInfo mocks base method.
func (m *MockManager) ListStoreInfo(ctx context.Context, size, page int) ([]*models_badgerdb_v4_management.DBInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreInfo", ctx, size, page)
	ret0, _ := ret[0].([]*models_badgerdb_v4_management.DBInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreInfo indicates an expected call of ListStoreInfo.
func (mr *MockManagerMockRecorder) ListStoreInfo(ctx, size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreInfo", reflect.TypeOf((*MockManager)(nil).ListStoreInfo), ctx, size, page)
}

// ListStoreMemoryInfo mocks base method.
func (m *MockManager) ListStoreMemoryInfo(ctx context.Context, size, page int) ([]*models_badgerdb_v4_management.DBMemoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreMemoryInfo", ctx, size, page)
	ret0, _ := ret[0].([]*models_badgerdb_v4_management.DBMemoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreMemoryInfo indicates an expected call of ListStoreMemoryInfo.
func (mr *MockManagerMockRecorder) ListStoreMemoryInfo(ctx, size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreMemoryInfo", reflect.TypeOf((*MockManager)(nil).ListStoreMemoryInfo), ctx, size, page)
}

// Paginate mocks base method.
func (m *MockManager) Paginate(it *badger.Iterator, size, page int) *badger.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", it, size, page)
	ret0, _ := ret[0].(*badger.Iterator)
	return ret0
}

// Paginate indicates an expected call of Paginate.
func (mr *MockManagerMockRecorder) Paginate(it, size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockManager)(nil).Paginate), it, size, page)
}

// Restart mocks base method.
func (m *MockManager) Restart() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart")
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockManagerMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockManager)(nil).Restart))
}

// Shutdown mocks base method.
func (m *MockManager) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockManager)(nil).Shutdown))
}

// ShutdownStores mocks base method.
func (m *MockManager) ShutdownStores() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShutdownStores")
}

// ShutdownStores indicates an expected call of ShutdownStores.
func (mr *MockManagerMockRecorder) ShutdownStores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownStores", reflect.TypeOf((*MockManager)(nil).ShutdownStores))
}

// Start mocks base method.
func (m *MockManager) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager)(nil).Start))
}

// ValidatePagination mocks base method.
func (m *MockManager) ValidatePagination(size, page int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePagination", size, page)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePagination indicates an expected call of ValidatePagination.
func (mr *MockManagerMockRecorder) ValidatePagination(size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePagination", reflect.TypeOf((*MockManager)(nil).ValidatePagination), size, page)
}
