// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4 (interfaces: Operator)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ../../internal/adaptors/datastore/badgerdb/v4/mocks/operations.go gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4 Operator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	saga "gitlab.com/pietroski-software-company/golang/devex/saga"
	v4 "gitlab.com/pietroski-software-company/lightning-db/internal/adaptors/datastore/badgerdb/v4"
	models_badgerdb_v4_management "gitlab.com/pietroski-software-company/lightning-db/internal/models/badgerdb/v4/management"
	models_badgerdb_v4_operation "gitlab.com/pietroski-software-company/lightning-db/internal/models/badgerdb/v4/operation"
	gomock "go.uber.org/mock/gomock"
)

// MockOperator is a mock of Operator interface.
type MockOperator struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorMockRecorder
	isgomock struct{}
}

// MockOperatorMockRecorder is the mock recorder for MockOperator.
type MockOperatorMockRecorder struct {
	mock *MockOperator
}

// NewMockOperator creates a new mock instance.
func NewMockOperator(ctrl *gomock.Controller) *MockOperator {
	mock := &MockOperator{ctrl: ctrl}
	mock.recorder = &MockOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperator) EXPECT() *MockOperatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOperator) Create(ctx context.Context, item *models_badgerdb_v4_operation.Item, opts *models_badgerdb_v4_operation.IndexOpts, retrialOpts *saga.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item, opts, retrialOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOperatorMockRecorder) Create(ctx, item, opts, retrialOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperator)(nil).Create), ctx, item, opts, retrialOpts)
}

// Delete mocks base method.
func (m *MockOperator) Delete(ctx context.Context, item *models_badgerdb_v4_operation.Item, opts *models_badgerdb_v4_operation.IndexOpts, retrialOpts *saga.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, item, opts, retrialOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOperatorMockRecorder) Delete(ctx, item, opts, retrialOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOperator)(nil).Delete), ctx, item, opts, retrialOpts)
}

// List mocks base method.
func (m *MockOperator) List(ctx context.Context, opts *models_badgerdb_v4_operation.IndexOpts, pagination *models_badgerdb_v4_management.Pagination) (models_badgerdb_v4_operation.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts, pagination)
	ret0, _ := ret[0].(models_badgerdb_v4_operation.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOperatorMockRecorder) List(ctx, opts, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperator)(nil).List), ctx, opts, pagination)
}

// ListValuesFromIndexingKeys mocks base method.
func (m *MockOperator) ListValuesFromIndexingKeys(ctx context.Context, opts *models_badgerdb_v4_operation.IndexOpts) (models_badgerdb_v4_operation.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListValuesFromIndexingKeys", ctx, opts)
	ret0, _ := ret[0].(models_badgerdb_v4_operation.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValuesFromIndexingKeys indicates an expected call of ListValuesFromIndexingKeys.
func (mr *MockOperatorMockRecorder) ListValuesFromIndexingKeys(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValuesFromIndexingKeys", reflect.TypeOf((*MockOperator)(nil).ListValuesFromIndexingKeys), ctx, opts)
}

// Load mocks base method.
func (m *MockOperator) Load(ctx context.Context, item *models_badgerdb_v4_operation.Item, opts *models_badgerdb_v4_operation.IndexOpts) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, item, opts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOperatorMockRecorder) Load(ctx, item, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOperator)(nil).Load), ctx, item, opts)
}

// Operate mocks base method.
func (m *MockOperator) Operate(dbInfo *models_badgerdb_v4_management.DBMemoryInfo) v4.Operator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operate", dbInfo)
	ret0, _ := ret[0].(v4.Operator)
	return ret0
}

// Operate indicates an expected call of Operate.
func (mr *MockOperatorMockRecorder) Operate(dbInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operate", reflect.TypeOf((*MockOperator)(nil).Operate), dbInfo)
}

// Upsert mocks base method.
func (m *MockOperator) Upsert(ctx context.Context, item *models_badgerdb_v4_operation.Item, opts *models_badgerdb_v4_operation.IndexOpts, retrialOpts *saga.RetrialOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, item, opts, retrialOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOperatorMockRecorder) Upsert(ctx, item, opts, retrialOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOperator)(nil).Upsert), ctx, item, opts, retrialOpts)
}
